### ISSUE TITLE
Openshift auto-deploy with Travis-CI integration

### ISSUE THREAD

**Issue by adoankim** [Soundphy/soundphy#12]
Hey there, I did some research about Openshift auto-deploy with Travis in the middle of the workflow and found an interesting [article](https://blog.openshift.com/using-generic-webhook-trigger-builds/).

TL;DR:

There is no direct integration between Openshift 3 and Travis, so we need to setup a proxy between Travis-CI and Openshift webhook calls to perform automatic deployments. This could be done by creating another Openshift project that holds the webhook proxy.

It will work without problem, the only issue is that after each deployment the data will be erased since the SQLite db file is stored in the Docker image. To solve this, we can place the db in a persistent volume, so the info will remains after each deploy.

**Comment by Peque** [comment]
@adoankim Thanks a lot for sharing this and opening the issue. :blush:

Creating another project to hold a webhook proxy seems like a hassle. However, I see it is possible to integrate the webhook with GitHub instead of Travis, right? I think that is OK as long as we are able to trigger the webhook just when new commits are pushed to master (only changes that already pass the tests will be merged into master).

I think we could first try that: create a webhook that triggers deployment from GitHub when commits are pushed to master.

When that is done we can open 2 more issues:

1. Persistent storage between deployments (higher priority).
1. Maybe think about triggering deployment from Travis (don't know if that is really a lot more convenient, and it will probably be fixed once OpenShift Online v3 gets out of "beta" and becomes the official version in production).

What do you think?

**Comment by adoankim** [comment]
Yeah, it sounds better. Since on master branch there will be only merged code that already passed the tests, there is no need to trigger the deploy from Travis. So yeah, a webhook that is triggered after merging on master could do the work :smile:.

**Comment by Peque** [comment]
@adoankim Great. Want to have a look at it? :stuck_out_tongue_winking_eye:

**Comment by adoankim** [comment]
@Peque Sure I can have a look at it. But before the integration, first I want to check the Github webhook and OpenShift documentation to have all the needed stuff prepared.

**Comment by Peque** [comment]
@adoankim Perfect. Do you have (or are planning to get) an OpenShift Online v3 preview account for your tests? If you don't and you don't want to create one, I could give you access to one (through other means of communication, of course).

Getting a preview account for yourself is actually very simple, you just need to [login with your GitHub account here](https://www.openshift.com/devpreview/register.html).

**Comment by adoankim** [comment]
@Peque Thanks. I created one, and once I've finished the setup I'll come back here to share the steps.

**Comment by adoankim** [comment]
Ok, I did some tests and got an auto-deployable project. Here are the steps I followed:

### In Openshift web panel:
 - Go to Builds section and open the desired project
 - On the upper right corner, under actions, select edit YAML
![image](https://cloud.githubusercontent.com/assets/1521546/23159600/b18933d8-f823-11e6-899a-08be0cbb82f0.png)
- Inside the config file, be sure that ref is pointing to the desired branch, by default is **master**

![image](https://cloud.githubusercontent.com/assets/1521546/23159359/c6fd8774-f822-11e6-967e-941527a49fda.png)
- In the same config file, take note of Github secret token under triggers
![image](https://cloud.githubusercontent.com/assets/1521546/23159368/d1a061a6-f822-11e6-8919-3ea561bcde1f.png)

- Now, go back to the build section (cancel edition), and go to builds configuration. At the right part of the section, you will see the webhook urls. Grab the Github one. 
![image](https://cloud.githubusercontent.com/assets/1521546/23159405/ed8ed866-f822-11e6-9ac1-28cf815ae356.png)


### GitHub side:
 - Inside the project, go to the settings/webhook/Add webhook
 - Fill the settings field with the OC config.

![image](https://cloud.githubusercontent.com/assets/1521546/23159447/11de1146-f823-11e6-8a45-75f6d2dbd40b.png)
 - After creating the webhook, be sure that the triggered deploy was successfully sent
![image](https://cloud.githubusercontent.com/assets/1521546/23159886/c24e4b62-f824-11e6-9c19-08a02d7b4068.png)

**Comment by Peque** [comment]
@adoankim Thanks a lot! :blush:

I would like to add this to the documentation. Would you like to do it? (so you keep the authorship) Otherwise, I can add it myself (and give credit to you, of course).

In order to do so, you can create a new file `/docs/source/deployment.rst` with the instructions. You can use `/docs/source/developers.rst` as a template.

I would try to minimize the use of embedded images in the instructions (i.e.: it is easy to use plain text for the YAML code you are showing and perhaps to describe other instructions). But if you need to add any, you can create a directory `docs/source/_static` to put them. Also, make sure to modify the `html_static_path` variable in `docs/source/conf.py`:

    html_static_path = ['logo', '_static']

**Comment by adoankim** [comment]
@Peque Nice, I'll add it to the docs and when is ready make the PR.

**Comment by adoankim** [comment]
PR created for this ticket: #13
